import 'reflect-metadata';
import { mkdirSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from '../src/app.module';

/**
 * Generates a static OpenAPI document for the thesis appendix.
 *
 *   - Builds the Nest application without listening on HTTP.
 *   - Runs Swagger document factory.
 *   - Writes JSON to ../docs/api/openapi.json (and a YAML side-by-side).
 */
async function main() {
  const app = await NestFactory.create(AppModule, { logger: ['warn', 'error'] });

  const config = new DocumentBuilder()
    .setTitle('PFOS API')
    .setDescription(
      'Personal Financial Operating System — REST API. Generated by `npm run docs:openapi`.',
    )
    .setVersion('0.1.0')
    .addBearerAuth(
      { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      'bearer',
    )
    .build();
  const document = SwaggerModule.createDocument(app, config);

  const outDir = resolve(__dirname, '..', '..', 'docs', 'api');
  mkdirSync(outDir, { recursive: true });

  const jsonPath = resolve(outDir, 'openapi.json');
  writeFileSync(jsonPath, JSON.stringify(document, null, 2), 'utf8');
  console.log(`Wrote ${jsonPath}`);

  await app.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
